notifications:
  email: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pipenv install"

# command to run tests
script:
  - "pipenv run pytest"