notifications:
  email: false
language: python
python:
  - "3.7"
  - "3.8"

# Required for Python 3.8 to work:
sudo: required
dist: bionic

# Install dependencies
before_install:
- pip install poetry
install:
- poetry install -v

# Run tests
script: pytest
